# Generated by Django 5.1.1 on 2024-10-20 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ACCOUNT', '0002_users_active_alter_users_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='active',
            new_name='is_status',
        ),
    ]
